- name: Общий пароль (Director <-> Storage Daemons) создан?
  assert:
    that:
      - sd_password | length > 0

- name: Установить общий пароль на Director и Storage Daemon узлах
  copy:
    content: 'Password = "{{ sd_password }}"'
    dest: /etc/bacula/bacula-sd-password.conf
    group: bacula
    owner: root
    mode: 0640
