- hosts: bacula_director
  tasks:
    - set_fact:
        # Общий пароль для Director'а и Storage Daemon'ов
        sd_password: "{{ lookup('password', '/dev/null length=22 chars=ascii_letters,digits,punctuation') }}"
        # Общий пароль для Director'а и File Daemon'ов
        fd_password: "{{ lookup('password', '/dev/null length=22 chars=ascii_letters,digits,punctuation') }}"
    - include_role:
        name: deploy_director

- hosts: bacula_storage_daemons
  tasks:
    - include_role:
        name: deploy_storage_daemons

- hosts: bacula_director:bacula_storage_daemons
  vars:
    sd_password: "{{hostvars['bacula_director']['sd_password']}}"
  tasks:
    - include_role:
        name: new_sd_password

- hosts: bacula_file_daemons
  tasks:
    - include_role:
        name: deploy_file_daemons

- hosts: bacula_director:bacula_file_daemons
  vars:
    fd_password: "{{hostvars['bacula_director']['fd_password']}}"
  tasks:
    - include_role:
        name: new_fd_password

- hosts: all
  tags: new-tls-credentials
  tasks:
    - include_role:
        name: setup_tls

- hosts: bacula_file_daemons
  tags:
    - new-tls-credentials
  tasks:
    - service:
        name: bacula-fd
        state: restarted
        enabled: yes

- hosts: bacula_storage_daemons
  tags:
    - new-tls-credentials
  tasks:
    - service:
        name: bacula-sd
        state: restarted
        enabled: yes

- hosts: bacula_director
  tags:
    - new-tls-credentials
  tasks:
    - service:
        name: bacula-dir
        state: restarted
        enabled: yes
