# ansible-playbook -v 00_set_env.yml -k --ask-become-pass
- hosts: all
  become: true
  become_method: su
  remote_user: sysadmin
  tasks:
    - lineinfile:
          path: /etc/hosts
          state: present
          line: 192.168.17.155 squid.vkr.alt
    - community.general.apt_rpm:
        pkg:
          bacula13-client
        state: present
        update_cache: yes
    - lineinfile:
          path: /root/.ssh/authorized_keys
          state: present
          line: 

